### ISSUE TITLE
Run Configuration: Allow selecting version

### ISSUE THREAD

**Issue by flying-sheep** [ant-druha/intellij-powershell#4]
I want to use PS core 6, not the builtin PS 2.

**Comment by ant-druha** [comment]
IDE uses the PS from your PATH. What is your OS? Do you have PS core 6 installed? Thanks.

**Comment by flying-sheep** [comment]
Windows 10, PS core 6.1.0 is installed!

**Comment by ant-druha** [comment]
Then you must be actually using this. Why do you think PS version 2 is used? You can check it by executing e.g. `(Get-Host).Version` in script.

**Comment by flying-sheep** [comment]
1. the startup message doesn’t say anything about 6.1.0 as it does when I open that one.
2. Executing a script containing `#Requires -Version 6` fails complaining that I only have version 2.

**Comment by ant-druha** [comment]
What startup message do you mean? Could you show a screenshot? 
Can you post the full command line that is executed and full output you get? Thanks.

**Comment by marcindabrowski** [comment]
I have a fresh installation of Windows and IntelliJ, and I have the same problem.
Run configuration open C:/WINDOWS/System32/WindowsPowerShell/v1.0/powershell.exe
not PowerShell 6. This path is visible at the first line of the Run window.
But when I open Terminal, it uses PowerShell 6.2.2

In my previous Windows it was working fine.

I'm not sure if it important - I've imported my project settings from the old machine.
I'm using IntelliJ 2019.2 and your plugin 2.0.2 version.

**Comment by marcindabrowski** [comment]
I agree with the global selector, but it will be great if users will have the ability to choose the version. Some modules are working only with 5.1, but in most cases, I prefer to use 7. 
So in such cases, I will have to switch the global version to use one run configuration and switch back to use another.
I know that this feature will be applicable mostly for Windows users, but I think it would be great to have it.

Now because there is no ability to set PowerShell version I can't use it, because the automatic selection is not working.

**Comment by ant-druha** [comment]
Fixed in 2.0.7 version.
