### ISSUE TITLE
Cannot pass multiple arguments with commas

### ISSUE THREAD

**Issue by fdw** [ant-druha/intellij-powershell#72]
Hi, I tried to start a script and pass multiple values to the same flag (f.e. `-t clean,build,unit,component`). However, it seems that this is not parsed correctly and instead only one string comprising everything is passed to the script.
Did I miss some setting?

**Comment by ForNeVeR** [comment]
Please clarify what exactly you are trying to do. I would assume you are passing these parameters to a run configuration, and then I expect them to be passed exactly as if they are passed via the command line (i.e. `pwsh -file yourFile.ps1 -t clean,build,etc`). Then this is by design (since it corresponds to the logic of the command-line invocation).

But it's possible I am incorrect and just misunderstand the issue.

**Comment by fdw** [comment]
Unfortunately, in the meantime I've switched systems and now I don't have access to the original configuration and project anymore, sorry.

I think it was about the scenario you described, where I expected the parameters to be split into an array, but they arrived as a string. Without the original script, however, I cannot reproduce the issue anymore.
