### ISSUE TITLE
IntelliJ Projector UI artifacts with the enabled plugin

### ISSUE THREAD

**Issue by pge-bw** [ant-druha/intellij-powershell#73]
Hi, there are UI artifacts with the Powershell plugin v. 2.0.7 enabled.
My setup: Ubuntu 20.04 + IntelliJ 2021.1.3 + Projector.
![Screen Shot 2021-08-27 at 12 54 01 PM](https://user-images.githubusercontent.com/71024523/131171422-5b26c8d7-7224-4aed-9057-bdf102d91c98.png)
![Screen Shot 2021-08-27 at 12 54 13 PM](https://user-images.githubusercontent.com/71024523/131171426-7bf22f4c-96b9-431a-b07b-fabbe984781b.png)

**Comment by ForNeVeR** [comment]
I am not sure what is the current status of Projector (seems to be [migrated into Gateway](https://lp.jetbrains.com/projector/)?), but the plugin does nothing with the panels you've shown. Please report to the maintainers of Projector or Gateway if this still causes problems, or share the IDE logs if you believe some wrong code in the plugin causes these rendering issues (e.g. if there are exceptions caused by the plugin during panel rendering, or anything like that).
